# Generated by Django 4.2.27 on 2025-12-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
    ]
